spring.application.name=data-jpa-books
spring.datasource.url=jdbc:mysql://localhost:3306/books
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable Hibernate statistics
spring.jpa.properties.hibernate.generate_statistics=true

# Log SQL statements
logging.level.org.hibernate.SQL=DEBUG

# Log query parameters (VERY IMPORTANT)
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE